language: php

php:
    - 5.5
    - 5.6
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

services:
    - redis-server
    - mongodb
    - rabbitmq

before_install:
    - sudo apt-get update

before_script:
    - echo "no" | pecl install apcu-beta
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
    - php app/console doctrine:database:create
    - php app/console doctrine:schema:create
    - php app/console doctrine:mongodb:create

script:
    - phpunit
    - echo "Running tests requiring tty"; phpunit --group tty

notifications:
    email:
        - johann_27@hotmail.fr