services:
    github.client:
        class: Certificationy\Bundle\GithubBundle\Api\Client
        arguments:
            - %github_login%
            - %github_password%
        calls:
            - [ "setLogger", [ @?logger ] ]

    github.security:
        class: Certificationy\Bundle\GithubBundle\Api\Security
        calls:
            - [ "setSecret", [ %kernel.secret% ] ]
            - [ "setLogger", [ @?logger ] ]

    github.status:
        class: Certificationy\Bundle\GithubBundle\Api\Status\Status
