services:
    github.bot:
        class: Gundam\Component\Bot\Bot
        abstract: true
        calls:
            - [ "setLogger", [ @?monolog.logger.github ] ]
        arguments:
            - @github.client
            - @github.security

    github.reviewer.bot:
        class: Certificationy\Bundle\GithubBundle\Bot\ReviewerBot
        parent: github.bot
        calls:
            - [ "setKernelRootDir", [ %kernel.root_dir% ] ]
            - [ "registerActionSubscriber", [ @github.reviewer.status_push.reaction ] ]
            - [ "registerActionListener", [ @github.reviewer.git_clone.reaction, 'git_clone' ] ]
            - [ "registerActionListener", [ @github.reviewer.check_parser.reaction, 'check' ] ]
            - [ "registerActionListener", [ @github.reviewer.check_structure.reaction, 'check' ] ]
            - [ "registerActionListener", [ @github.reviewer.check_uniqueness.reaction, 'check' ] ]
            - [ "registerActionListener", [ @github.reviewer.check_context.reaction, 'check' ] ]
            - [ "registerActionListener", [ @github.reviewer.persistence.reaction, 'persist' ] ]
            - [ "registerActionListener", [ @github.reviewer.remove_folder.reaction, 'remove_folder' ] ]

    github.reviewer.status_push.reaction:
        class: Gundam\Component\Bot\Reaction\SwitchCommitStatusReaction
        arguments:
            - @router

    github.reviewer.git_clone.reaction:
        class: Certificationy\Bundle\GithubBundle\Bot\Certificationy\Reaction\GitLocaleCloneReaction
        arguments:
            - %github_login%
            - %github_password%
        calls:
            - [ "setLogger", [ @?monolog.logger.github ] ]

    github.reviewer.check_parser.reaction:
        class: Certificationy\Bundle\GithubBundle\Bot\Certificationy\Reaction\CheckParserReaction

    github.reviewer.check_structure.reaction:
        class: Certificationy\Bundle\GithubBundle\Bot\Certificationy\Reaction\CheckStructureReaction

    github.reviewer.check_uniqueness.reaction:
        class: Certificationy\Bundle\GithubBundle\Bot\Certificationy\Reaction\CheckUniquenessReaction

    github.reviewer.check_context.reaction:
        class: Certificationy\Bundle\GithubBundle\Bot\Certificationy\Reaction\CheckContextReaction

    github.reviewer.persistence.reaction:
        class: Certificationy\Bundle\GithubBundle\Bot\Certificationy\Reaction\PersistenceReaction
        arguments:
            - @doctrine.odm.mongodb.document_manager

    github.reviewer.remove_folder.reaction:
        class: Certificationy\Bundle\GithubBundle\Bot\Certificationy\Reaction\RemoveFolderReaction
        calls:
            - [ "setLogger", [ @?monolog.logger.github ] ]
