imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: %debug_toolbar%
    intercept_redirects: %debug_redirects%

jms_serializer:
    metadata:
        cache: ~

monolog:
    handlers:
        main:
            type: buffer
            action_level: warning
            handler: grouped
        grouped:
            type: group
            members: [ application, login ]
        application:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        login:
            type:   stream
            path:   "%kernel.logs_dir%/auth_%kernel.environment%.log"
            level: info
            channels: security
        console:
            type: console
            bubble: false

assetic:
    use_controller: %use_assetic_controller%
