imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: %debug_toolbar%
    intercept_redirects: %debug_redirects%

jms_serializer:
    metadata:
        cache: ~

monolog:
    channels: [ "github", "certy" ]
    handlers:
        application:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            channels: [ 'request', 'event', 'templating', 'router' ]
        security:
            type: stream
            path: "%kernel.logs_dir%/auth_%kernel.environment%.log"
            channels: ['security' ]
        console:
            type: console
            bubble: false
        redis:
            type: stream
            path: "%kernel.logs_dir%/redis_%kernel.environment%.log"
            channels: [ 'snc_redis' ]
        doctrine:
            type: stream
            path: "%kernel.logs_dir%/doctrine_%kernel.environment%.log"
            channels: [ 'doctrine' ]
        github:
            type: stream
            path: "%kernel.logs_dir%/github_%kernel.environment%.log"
            channels: [ 'github' ]

assetic:
    use_controller: %use_assetic_controller%
