imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    assets_version: v2.0.0

framework:
    esi: ~
    fragments:
        path: /_proxy
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %assets_version%
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: 'Certificationy'
        cookie_domain: %domain%
        handler_id:  ~
    http_method_override: true
    session:
        cookie_lifetime: 31536000
        cookie_domain: %domain%
        name: certificationy
        save_path: null

# Twig Configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        ga_tracking: %google_analytics_id%
    form:
        resources:
            - '::form_layout.html.twig'

monolog:
    channels: [ "github", "certy" ]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    delivery_address: no-reply@certificationy.com

fos_user:
    registration:
        form:
            type: certificationy_user_registration
    db_driver: orm
    firewall_name: main
    user_class: Certificationy\Bundle\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: false

hwi_oauth:
    firewall_name: main
    connect:
        confirmation: true
        account_connector: certificationy.user.provider.fosub_bridge

    resource_owners:
        github:
            type: github
            client_id: %github_client_id%
            client_secret: %github_client_secret%
            scope: "user:email"

    fosub:
        username_iterations: 30
        properties:
            github: githubID

braincrafted_bootstrap:
    output_dir: %kernel.root_dir%/Resources/bootstrap-custom/bootstrap.less
    assets_dir: %kernel.root_dir%/Resources/assets/bootstrap/less/bootstrap.less
    jquery_path: %kernel.root_dir%/Resources/assets/jquery/jquery.js
    less_filter: less
    customize:
            variables_file: %kernel.root_dir%/../src/Certificationy/Bundle/WebBundle/Resources/private/less/variable.less
    auto_configure:
        assetic: false
        twig: false
        knp_menu: true
        knp_paginator: true

jms_serializer:
    metadata:
        debug: %kernel.debug%

doctrine_mongodb:
    connections:
        default:
            server: %mongodb_server%
            options: {}
    default_database: %mongodb_collection%
    document_managers:
        default:
            auto_mapping: true

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dsn%/%redis_default_client%

        session:
            type: predis
            alias: session
            dsn: %redis_dsn%/%redis_session_client%

        counter:
            type: predis
            alias: counter
            dsn: %redis_dsn%/%redis_counter_client%
    session:
        client: session
        prefix: session:main
        use_as_default: true

#swarrot:
#    provider: pecl
#    default_connection: rabbitmq
#    default_command: swarrot.command.base
#    processors_stack:
#        signal_handler: 'Swarrot\Processor\SignalHandler\SignalHandlerProcessor'
#        ack: 'Swarrot\Processor\Ack\AckProcessor'
#        retry: 'Swarrot\Processor\Retry\RetryProcessor'
#        exception_catcher: 'Swarrot\Processor\ExceptionCatcher\ExceptionCatcherProcessor'
#    connections:
#        rabbitmq:
#            host: %rabbitmq_host%
#            port: %rabbitmq_port%
#            login: %rabbitmq_login%
#            password: %rabbitmq_password%
#            vhost: '/'
#    consumers:
#        certification:
#            processor: certy.certification.result_processor
#            extras:
#                retry_exchange: certification
#                retry_attempts: 3
#                retry_routing_key_pattern: 'retry_%%attempt%%'
#                max_messages: 2
#    messages_types:
#        compute_certification:
#            connection: rabbitmq
#            exchange: certification
#            routing_key: ~

certificationy_certy:
    debug: %kernel.debug%
    provider:
        file:
            root_dir: %kernel.root_dir%/Resources/certificationy-data
    calculator:
        class: Certificationy\Component\Certy\Calculator\Calculator
        delegator: ~ #rabbitmq

ekino_new_relic:
    enabled: %kernel.debug%
    application_name: Certificationy
    api_key: %new_relic_api_key%
    license_key: %new_relic_license_key%
    xmit: false
    logging: false
    instrument: true
    log_exceptions: true
    log_commands: true
    using_symfony_cache: false
    transaction_naming: controller
    transaction_naming_service: ~
    ignored_routes: []
    ignored_paths: []
    ignored_commands: []

services:
    twig.extension.i18n:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }