imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: %debug_toolbar%
    intercept_redirects: %debug_redirects%

jms_serializer:
    metadata:
        cache: ~

monolog:
    handlers:
        application:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/application.log"
            channels: [ 'request', 'event', 'templating', 'router' ]
        security:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/security.log"
            channels: ['security' ]
        console:
            type: console
            bubble: false
        redis:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/redis.log"
            channels: [ 'snc_redis' ]
        doctrine:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/doctrine.log"
            channels: [ 'doctrine' ]
        github:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/github.log"
            channels: [ 'github' ]
        certy:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/certy.log"
            channels: [ 'certy' ]
