imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: %debug_toolbar%
    intercept_redirects: %debug_redirects%

#monolog:
#    handlers:
#        main:
#            type:   stream
#            path:   "%kernel.logs_dir%/%kernel.environment%.log"
#            level:  debug
#            formatter:
#        console:
#            type: console
#            bubble: false

monolog:
    handlers:
        main:
            type: buffer
            action_level: warning
            handler: grouped
        grouped:
            type: group
            members: [ application, login ]
        application:
            type: service
            id: snc_redis.monolog.handler
            level: debug
        login:
            type: service
            id: snc_redis.monolog.handler
            level: info
            channels: security

assetic:
    use_controller: %use_assetic_controller%
