imports:
    - { resource: config.yml }

framework:
    validation:
        cache: apc

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
        grouped:
            type: group
            members: [ application, swift ]
        application:
            type: service
            id: snc_redis.monolog.handler
            level: debug
        swift:
            type: swift_mailer
            type:               swift_mailer
            from_email:         log@certificationy.com
            to_email:           johann_27@hotmail.com
            subject:            "[LOG][CERTIFICATIONY]"
            level:              debug
        login:
            type: service
            id: snc_redis.monolog.handler
            level: info
            channels: security