imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    assets_version: v1.0.1

framework:
    esi: ~
    fragments:
        path: /_proxy
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %assets_version%
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: 'Certificationy'
        cookie_domain: %domain%
        handler_id:  ~
    http_method_override: true
    session:
        cookie_lifetime: 31536000
        cookie_domain: %domain%
        name: certificationy

# Twig Configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        ga_tracking: %google_analytics_id%
    form:
        resources:
            - 'BraincraftedBootstrapBundle::layout.html.twig'

# Assetic Configuration
assetic:
    debug: "%kernel.debug%"
    use_controller: false
    bundles: [ ]
    filters:
        yui_js:
            jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar'
            apply_to: '\.js$'
            preserve_comments: false
        yui_css:
            jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar'
            apply_to: '\.css$'
            preserve_comments: false
        closure:
             jar: '%kernel.root_dir%/Resources/java/compiler.jar'
             apply_to: '\.js$'
        less:
            node: /usr/bin/nodejs
            node_paths: [ /usr/lib/node_modules ]
            apply_to: "\.less$"
        cssrewrite: ~
    assets:
        report_css:
            inputs:
                - %kernel.root_dir%/Resources/CertificationyCertyBundle/private/less/report.less
            filters:
                - less
                - cssrewrite
                - yui_css
            output: css/report.css
        user_css:
            inputs:
                - @CertificationyUserBundle/Resources/private/less/user.less
            filters:
                - less
                - yui_css
            output: css/user.css
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/Resources/less/bootstrap.less
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
            filters:
                - less
                - cssrewrite
                - yui_css
            output: css/bootstrap.css
        font_awesome_css:
            inputs:
                - %kernel.root_dir%/../vendor/fortawesome/font-awesome/less/font-awesome.less
            filters:
                - less
                - cssrewrite
                - yui_css
            output: css/font-awesome.css
        bootstrap_theme_css:
            inputs:
                - @CertificationyWebBundle/Resources/public/css/fonts.css
                - %kernel.root_dir%/../web/components/devicons/css/devicons.css
                - @CertificationyWebBundle/Resources/private/less/global.less
            filters:
                - less
                - yui_css
            output: css/bootstrap-theme.css
        bootstrap_social_css:
            inputs:
                - @CertificationyWebBundle/Resources/private/less/bootstrap-social.less
            filters:
                - less
                - yui_css
            output: css/bootstrap-social.css
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js
            filters:
                - yui_js
                - closure
            output: js/bootstrap.js
        jquery:
            inputs:
                - %kernel.root_dir%/../web/components/jquery/jquery.js
            filters:
                - yui_js
                - closure
            output: js/jquery.js

monolog:
    channels: [ "github", "certy" ]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    delivery_address: no-reply@certificationy.com

fos_user:
    registration:
        form:
            type: certificationy_user_registration
    db_driver: orm
    firewall_name: main
    user_class: Certificationy\Bundle\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: false

hwi_oauth:
    firewall_name: main
    connect:
        confirmation: true
        account_connector: certificationy.user.provider.fosub_bridge

    resource_owners:
        github:
            type: github
            client_id: %github_client_id%
            client_secret: %github_client_secret%
            scope: "user:email"

    fosub:
        username_iterations: 30
        properties:
            github: githubID

braincrafted_bootstrap:
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/components/jquery/jquery.js
    less_filter: less
    customize:
            variables_file: %kernel.root_dir%/../src/Certificationy/Bundle/WebBundle/Resources/private/less/variable.less
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true

jms_serializer:
    metadata:
        debug: %kernel.debug%

doctrine_mongodb:
    connections:
        default:
            server: %mongodb_server%
            options: {}
    default_database: %mongodb_collection%
    document_managers:
        default:
            auto_mapping: true

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dsn%/%redis_default_client%

        session:
            type: predis
            alias: session
            dsn: %redis_dsn%/%redis_session_client%

        counter:
            type: predis
            alias: counter
            dsn: %redis_dsn%/%redis_counter_client%
    session:
        client: session
        prefix: session:main
        use_as_default: true

#swarrot:
#    provider: pecl
#    default_connection: rabbitmq
#    default_command: swarrot.command.base
#    processors_stack:
#        signal_handler: 'Swarrot\Processor\SignalHandler\SignalHandlerProcessor'
#        ack: 'Swarrot\Processor\Ack\AckProcessor'
#        retry: 'Swarrot\Processor\Retry\RetryProcessor'
#        exception_catcher: 'Swarrot\Processor\ExceptionCatcher\ExceptionCatcherProcessor'
#    connections:
#        rabbitmq:
#            host: %rabbitmq_host%
#            port: %rabbitmq_port%
#            login: %rabbitmq_login%
#            password: %rabbitmq_password%
#            vhost: '/'
#    consumers:
#        certification:
#            processor: certy.certification.result_processor
#            extras:
#                retry_exchange: certification
#                retry_attempts: 3
#                retry_routing_key_pattern: 'retry_%%attempt%%'
#                max_messages: 2
#    messages_types:
#        compute_certification:
#            connection: rabbitmq
#            exchange: certification
#            routing_key: ~

certificationy_certy:
    debug: %kernel.debug%
    provider:
        file:
            root_dir: %kernel.root_dir%/Resources/certificationy-data
    calculator:
        class: Certificationy\Component\Certy\Calculator\Calculator
        delegator: ~ #rabbitmq

services:
    twig.extension.i18n:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }