imports:
    - { resource: config.yml }

framework:
    validation:
        cache: apc

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        application:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/application.log"
            channels: [ 'request', 'router' ]
        security:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/security.log"
            channels: ['security' ]
        console:
            type: console
            bubble: false
        redis:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/redis.log"
            channels: [ 'snc_redis' ]
        doctrine:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/doctrine.log"
            channels: [ 'doctrine' ]
        swift:
            type: swift_mailer
            from_email: logger@certificationy.com
            to_email: johann_27@hotmail.fr
            subject: "[certificationy-web-platform][logger]"
            level: error
        github:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/github.log"
            channels: [ 'github' ]
        certy:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/certy.log"
            channels: [ 'certy' ]
