imports:
    - { resource: config.yml }

framework:
    validation:
        cache: apc

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: grouped
        grouped:
            type: group
            members: [application, security, redis, doctrine]
        application:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            channels: [ 'request', 'event', 'templating', 'router' ]
        security:
            type: stream
            path: "%kernel.logs_dir%/auth_%kernel.environment%.log"
            channels: ['security' ]
        console:
            type: console
            bubble: false
        redis:
            type: stream
            path: "%kernel.logs_dir%/redis_%kernel.environment%.log"
            channels: [ 'snc_redis' ]
        doctrine:
            type: stream
            path: "%kernel.logs_dir%/doctrine_%kernel.environment%.log"
            channels: [ 'doctrine' ]
        swift:
            type: swift_mailer
            from_email: logger@certificationy.com
            to_email: johann_27@hotmail.fr
            subject: "[certificationy-web-platform][logger]"
            level: debug
        github:
            type: stream
            path: "%kernel.logs_dir%/github_%kernel.environment%.log"
            channels: [ 'github' ]
