certificationy_site_routing:
    resource: @CertificationyWebBundle/Resources/config/routing/site.yml

certificationy_help_routing:
    resource: @CertificationyWebBundle/Resources/config/routing/help.yml
    prefix: /help
