parameters:

services:
    certificationy.web.abstract_controller:
        class: Certificationy\Bundle\WebBundle\Controller\AbstractController
        scope: request
        calls:
            - [ "setRequestStack", [ @request_stack ] ]
            - [ "setEngine", [ @templating ] ]
            - [ "setMenuBuilder", [ @certificationy.training.menu ] ]
            - [ "setRouter", [ @router ] ]
            - [ "setSecurityContext", [ @security.context ] ]

    certificationy.web.site_controller:
        class: Certificationy\Bundle\WebBundle\Controller\SiteController
        parent: certificationy.web.abstract_controller
        scope: request
        arguments:
            - %kernel.root_dir%
            - @certificationy.certification.manager

    certificationy.web.help.controller:
        class: Certificationy\Bundle\WebBundle\Controller\HelpController
        parent: certificationy.web.abstract_controller
        scope: request

    certificationy.web.menu_builder:
        class: Certificationy\Bundle\WebBundle\Menu\WebBuilder
        arguments:
            - @knp_menu.factory

    certificationy.web.menu:
        class: Knp\Menu\MenuItem
        factory_service: certificationy.web.menu_builder
        factory_method: createWebMenu
        arguments:
            - @request
        scope: request
        tags:
            - { name: knp_menu.menu, alias: web }
