parameters:

services:
    certificationy.web.abstract_controller:
        class: Certificationy\Bundle\WebBundle\Controller\AbstractController
        calls:
            - [ "setRequestStack", [ @request_stack ] ]
            - [ "setEngine", [ @templating ] ]
            - [ "setMenuCollection", [ { } ] ]
            - [ "setRouter", [ @router ] ]

    certificationy.web.site_controller:
        class: Certificationy\Bundle\WebBundle\Controller\SiteController
        parent: certificationy.web.abstract_controller
