certificationy_train_session_routing:
    resource: @CertificationyTrainingBundle/Resources/config/routing/training.yml
    prefix: /

training:
    path: /{name}
    defaults:
        _controller: certificationy.training.training_controller:indexAction
    requirements:
        _method: GET
