services:
    certificationy.training.menu_builder:
        class: Certificationy\Bundle\TrainingBundle\Menu\TrainingBuilder
        arguments:
            - @knp_menu.factory
            - @translator
            - @certificationy.certification.manager

    certificationy.training.menu:
        class: Knp\Menu\MenuItem
        factory_service: certificationy.training.menu_builder
        factory_method: createTrainingMenu
        arguments:
            - @request
        scope: request
        tags:
            - { name: knp_menu.menu, alias: training }

    certificationy.training.training_controller:
        class: Certificationy\Bundle\TrainingBundle\Controller\TrainingController
        parent: certificationy.web.abstract_controller
        scope: request
        arguments:
            - @certificationy.certification.manager

    certificationy.twig.extension:
        class: Certificationy\Bundle\TrainingBundle\Twig\Extension\TrainingExtension
        arguments:
            - @translator
        tags:
            - { name: twig.extension }

    certificationy.certification_loader.twig.extension:
        class: Certificationy\Bundle\TrainingBundle\Twig\Extension\ContributingExtension
        arguments:
            -  @twig.loader
            - %certy_file_provider_root_dir%
        calls:
            - [ addCertificationTemplateDir, [ @certificationy.certification.manager ] ]
        tags:
            - { name: twig.extension }
