parameters:
    symfony_certification_name: 'symfony2'

services:
    certificationy.certification.manager:
        class: Certificationy\Bundle\TrainingBundle\Manager\CertificationManager
        arguments:
            - @certy.certification.factory
