services:
    certificationy.certification.manager:
        class: Certificationy\Bundle\TrainingBundle\Manager\CertificationManager
        arguments:
            - @certy.certification.factory
            - @certy.certification.builder
            - @snc_redis.default
            - @jms_serializer
            - @monolog.logger.certy
        calls:
            - [ "setBasePath", [ %certy_file_provider_root_dir% ] ]
            - [ "setDebug", [ %certy_debug% ] ]

    certificationy.report.persister:
        class: Certificationy\Bundle\TrainingBundle\EventListener\StoreCertificationReportListener
        arguments:
            - @doctrine.odm.mongodb.document_manager
            - @security.context
        tags:
            - { name: kernel.event_listener, event: certy.certification.post_computation, method: store }

    certificationy.metrics.listener:
        class: Certificationy\Bundle\TrainingBundle\EventListener\MetricsCounterListener
        arguments:
            - @snc_redis.counter
        tags:
            - { name: kernel.event_listener, event: certy.certification.submission, method: increment }
