parameters:
    certificationy.user.provider.fosub_bridge.class: Certificationy\Bundle\UserBundle\Security\Core\User\FOSUBUserProvider
    complete_registration_form_name: certificationy_complete_registration

services:
    certificationy.user.provider.fosub_bridge:
        class: %certificationy.user.provider.fosub_bridge.class%
        arguments: [ @fos_user.user_manager, { github: githubID }, @snc_redis.default ]

    certificationy.user.repository:
        class: Certificationy\Bundle\UserBundle\Repository\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [ 'CertificationyUserBundle:User']

    certificationy.user.menu_builder:
        class: Certificationy\Bundle\UserBundle\Menu\UserBuilder
        arguments:
            - @knp_menu.factory
            - @translator
            - @security.context

    certificationy.user.menu:
        class: Knp\Menu\MenuItem
        factory_service: certificationy.user.menu_builder
        factory_method: createUserMenu
        arguments:
            - @request
        scope: request
        tags:
            - { name: knp_menu.menu, alias: user }

    certificationy.user.gravatar.extension:
        class: Certificationy\Bundle\UserBundle\Twig\Extension\GravatarExtension
        arguments:
            - @security.context
            - @fos_user.user_manager
        tags:
            -  { name: twig.extension }

    certificationy.user.registration_type:
        class: Certificationy\Bundle\UserBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: 'certificationy_user_registration' }

    certificationy.user.complete_registration.listener:
        class: Certificationy\Bundle\UserBundle\EventListener\CompleteUserRegistrationListener
        arguments:
            - @security.context
            - @router
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    certificationy.user.complete_registration_form.type:
        class: Certificationy\Bundle\UserBundle\Form\Type\CompleteRegistrationType
        arguments:
            - %fos_user.model.user.class%
        tags:
            - { name: form.type, alias: %complete_registration_form_name%  }

    certificationy.user.complete_registration_form.handler:
        class: Certificationy\Bundle\UserBundle\Form\Handler\CompleteRegistrationFormHandler
        parent: certy.form.handler
        arguments:
            - @fos_user.user_manager
        calls:
            - [ "setName", [ %complete_registration_form_name% ] ]
